name: Haskell CI

on:
  push:
    branches: [ main, amazonka2 ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Cache Key
      id: cache_key
      run: echo "key=$(md5sum stack.yaml | awk '{print $1}')" >> $GITHUB_ENV

    - name: Cache Dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ~/.stack
        key: ${{ matrix.os }}-${{ env.key }}

    - name: Build Snapshot
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        stack --no-terminal test --bench --only-snapshot

    - name: Build & Test
      run: |
        stack --no-terminal test --bench --no-run-benchmarks
        stack install
        mkdir dist
        cp $HOME/.local/bin/s3up dist

    - name: Store Artifact
      uses: actions/upload-artifact@v3
      with:
        name: s3up-${{ matrix.os }}
        path: dist
